nodeLinker: hoisted

packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  '@nestjs/core': true
  '@prisma/client': true
  '@prisma/engines': true
  '@scarf/scarf': true
  bcrypt: true
  msgpackr-extract: true
  prisma: true
  unrs-resolver: true
  sharp: true
  core-js: false
  '@firebase/util': true
  protobufjs: true
