import { MD3LightTheme, type MD3Theme } from 'react-native-paper';

export const palette = {
  background: '#f5f4ee',
  surface: '#ffffff',
  surfaceMuted: '#eef1eb',
  surfaceStrong: '#dfe5dc',
  primary: '#1f6f4a',
  primaryStrong: '#0f3528',
  secondary: '#e86f3d',
  secondaryMuted: '#fff0df',
  text: '#18251f',
  textMuted: '#68736d',
  border: '#d9dfd4',
  success: '#137b59',
  warning: '#b66a00',
  error: '#ba1a1a',
  info: '#2768bd',
  purple: '#7d4cc2',
  rose: '#cf3f5d',
  teal: '#0f7774',
  amber: '#d98b16',
  indigo: '#4d66c3',
  slate: '#152620',
  white: '#ffffff',
} as const;

export const mobileColors = {
  primary: palette.primary,
  primaryStrong: palette.primaryStrong,
  onPrimary: palette.white,
  primaryContainer: '#dff2e4',
  onPrimaryContainer: palette.primaryStrong,
  secondary: palette.secondary,
  onSecondary: palette.white,
  secondaryContainer: palette.secondaryMuted,
  onSecondaryContainer: '#c2410c',
  orange: palette.secondary,
  orangeContainer: '#ffedd5',
  onOrangeContainer: '#c2410c',
  blue: palette.info,
  blueContainer: '#dbeafe',
  onBlueContainer: '#1d4ed8',
  purple: palette.purple,
  purpleContainer: '#ede9fe',
  onPurpleContainer: '#6d28d9',
  rose: palette.rose,
  roseContainer: '#ffe4e6',
  onRoseContainer: '#be123c',
  teal: palette.teal,
  tealContainer: '#ccfbf1',
  onTealContainer: '#0f766e',
  amber: palette.amber,
  amberContainer: '#fef3c7',
  onAmberContainer: '#b45309',
  indigo: palette.indigo,
  indigoContainer: '#e0e7ff',
  onIndigoContainer: '#4338ca',
  heroDriver: '#17352e',
  heroCampaign: '#40265e',
  heroBulk: '#673919',
  heroBlue: '#163568',
  background: palette.background,
  surface: palette.surface,
  surfaceContainerLowest: palette.surface,
  surfaceContainerLow: palette.surfaceMuted,
  surfaceContainerHighest: palette.surfaceStrong,
  surfaceVariant: palette.surfaceMuted,
  onSurface: palette.text,
  onSurfaceVariant: palette.textMuted,
  outline: palette.border,
  outlineVariant: '#e5e9df',
  success: palette.success,
  warning: palette.warning,
  error: palette.error,
  danger: palette.error,
  info: palette.info,
  muted: palette.surfaceStrong,
  onMuted: '#4b5563',
  navActive: palette.primary,
  navInactive: '#667085',
  successContainer: '#dcfce7',
  onSuccessContainer: '#15803d',
  warningContainer: '#fef3c7',
  onWarningContainer: '#b45309',
  errorContainer: '#ffdad6',
  onErrorContainer: '#8b1a1a',
  infoContainer: '#dbeafe',
  onInfoContainer: '#1d4ed8',
  neutralContainer: '#f3f4f6',
  onNeutralContainer: '#6b7280',
  cream: '#fbf7ef',
  mint: '#edf8ef',
  coral: '#fff0e8',
  ink: '#111d18',
  white: palette.white,
} as const;

export const spacing = {
  xs: 4,
  sm: 8,
  md: 12,
  lg: 16,
  xl: 20,
  xxl: 24,
  section: 32,
} as const;

export const radius = {
  sm: 8,
  md: 12,
  lg: 16,
  xl: 22,
  pill: 999,
} as const;

export const elevation = {
  card: {
    shadowColor: '#102018',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.1,
    shadowRadius: 24,
    elevation: 3,
  },
  pressed: {
    shadowColor: '#102018',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.07,
    shadowRadius: 12,
    elevation: 1,
  },
} as const;

export const paperDefaults = {
  button: {
    borderRadius: radius.md,
    contentPaddingVertical: 4,
  },
  input: {
    dense: true,
    borderRadius: radius.sm,
  },
  card: {
    borderRadius: radius.md,
    elevation: 1,
  },
} as const;

export const typography = {
  title: {
    fontWeight: '700',
    letterSpacing: 0,
    color: palette.text,
  },
  body: {
    letterSpacing: 0,
    color: palette.text,
  },
  muted: {
    letterSpacing: 0,
    color: palette.textMuted,
  },
} as const;

export const appTheme: MD3Theme = {
  ...MD3LightTheme,
  roundness: radius.md,
  colors: {
    ...MD3LightTheme.colors,
    primary: palette.primary,
    onPrimary: '#ffffff',
    primaryContainer: '#dff2e4',
    onPrimaryContainer: palette.primaryStrong,
    secondary: palette.secondary,
    onSecondary: '#ffffff',
    secondaryContainer: palette.secondaryMuted,
    onSecondaryContainer: '#5f1f0d',
    background: palette.background,
    onBackground: palette.text,
    surface: palette.surface,
    surfaceDisabled: '#e5e7df',
    onSurfaceDisabled: '#8a9385',
    onSurface: palette.text,
    surfaceVariant: palette.surfaceMuted,
    onSurfaceVariant: palette.textMuted,
    outline: palette.border,
    outlineVariant: palette.border,
    error: palette.error,
    onError: '#ffffff',
    errorContainer: '#ffdad6',
    onErrorContainer: '#410002',
  },
};
